---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: av-helloworld-channel
  namespace: av-helloworld
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management/application-samples.git
