---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: av-helloworld-app-subscription
  namespace: av-helloworld
  labels:
    app: helloworld-app
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
    apps.open-cluster-management.io/github-path: helloworld
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: av-helloworld/helloworld-channel
  placement:
    placementRef:
      name: av-helloworld-app-placement
      kind: Placement
